name: Generate deltas

on:
  workflow_call:
    inputs: &inputs
      variant:
        description: Which variant to generate deltas for
        type: string
        required: true
      recreate:
        description: Recreate all deltas at the latest format
        type: boolean
        required: false
        default: false
      push:
        description: Push the delta
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs: *inputs

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  matrix:
    name: atomic-arch:${{ inputs.variant }} deltas
    runs-on: ubuntu-latest
    container: &container
      image: ghcr.io/eeems/atomic-arch-builder:latest
      options: >-
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device /dev/fuse
        --tmpfs /tmp
        --tmpfs /run
        --userns=host
        -v /var/lib/containers:/var/lib/containers
        -v /:/run/host
    outputs:
      variant-matrix: ${{ steps.matrix.outputs.JSON_CONTENT }}
      items: ${{ steps.matrix.outputs.items }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Ensure .docker exists
        run: |
          mkdir -p /github/home/.docker
          if ! [ -f /github/home/.docker/config.json ];then
            echo '{"auths":{}}' > /github/home/.docker/config.json
          fi

      - name: Login to ghcr
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - name: Get matrix
        id: matrix
        shell: bash
        run: |
          args=""
          if [[ "${{ inputs.recreate }}" != "true" ]];then
            args="$args --missing"
          fi
          mkdir -p /run/podman
          podman system service --time 0 unix:///run/podman/podman.sock &
          data="$(./make.py get-deltas --json $args ${{ inputs.variant }})"
          items="$(echo "$data" | jq -c 'length')"
          echo 'JSON_CONTENT<<EOF' >> $GITHUB_OUTPUT
          if [[ $items -gt 0 ]];then
            echo "$data" | jq -c '{"include": .}' >> $GITHUB_OUTPUT
          else
            echo '{"include":[{"a":"","b":"","tag":""}]}' >> $GITHUB_OUTPUT
          fi
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "items=$items" >> $GITHUB_OUTPUT
          kill $(jobs -p)
        env:
          TMPDIR: ${{ runner.temp }}
  run:
    name: ${{ matrix.a }} to ${{matrix.b}}
    if: ${{ needs.matrix.outputs.items > 0 }}
    runs-on: ubuntu-latest
    container: *container
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.variant-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-container

      - name: Login to dockerhub
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - uses: ./.github/actions/mask-registry-passwords

      - name: Free up space
        uses: ./.github/actions/cleanup
        with:
          root: /run/host

      - uses: ./.github/actions/manifest-cache-restore
        with:
          key: ${{ inputs.variant }}
          artifact: true

      - name: Build
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            args=""
            if [[ "${{ inputs.recreate }}" == "true" ]];then
              args="$args --force"
            fi
            if [[ "${{ inputs.push }}" == "true" ]];then
              args="$args --push"
            fi
            ./make.py delta $args --explicit ${{ matrix.a }} ${{ matrix.b }}
        env:
          TMPDIR: ${{ github.workspace }}/.tmp

      - uses: ./.github/actions/manifest-cache-update
        with:
          key: ${{ inputs.variant }}
          artifact: true

      - name: Export image
        id: export
        if: ${{ ! inputs.push }}
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            name=$(python <<EOF
            import make
            from _os.podman import hex_to_base62
            from _os.podman import image_digest
            from _os import REPO
            a = hex_to_base62(image_digest(f"{REPO}:${{ matrix.a }}"))
            b = hex_to_base62(image_digest(f"{REPO}:${{ matrix.b }}"))
            print(f"_diff-{a}-{b}")
            EOF
            )
            image=$(python <<EOF
            import make
            from _os import REPO
            print(REPO)
            EOF
            )
            podman save "$image:$name" | zstd -o $name.tar.zstd
            echo \
              "outputs={\"name\":\"$name\",\"path\":\"$name.tar.zstd\"}" \
            >> $GITHUB_OUTPUT

      - name: Upload ${{ fromJson(steps.export.outputs.outputs).name }} image
        if: ${{ !inputs.push }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ fromJson(steps.export.outputs.outputs).name }}
          path: ${{ fromJson(steps.export.outputs.outputs).path }}
          if-no-files-found: ignore
