name: Generate deltas

on:
  workflow_call:
    inputs: &inputs
      variant:
        description: Which variant to generate deltas for
        type: string
        required: true
      recreate:
        description: Recreate all deltas at the latest format
        type: boolean
        required: false
        default: false
      push:
        description: Push the delta
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs: *inputs

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  matrix:
    name: atomic-arch:${{ inputs.variant }} deltas
    runs-on: ubuntu-latest
    container: &container
      image: ghcr.io/eeems/atomic-arch-builder:latest
      options: >-
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device /dev/fuse
        --tmpfs /tmp
        --tmpfs /run
        --userns=host
        -v /var/lib/containers:/var/lib/containers
        -v /:/run/host
    outputs:
      variant-matrix: ${{ fromJson(steps.matrix.outputs.outputs).matrix }}
      items: ${{ fromJson(steps.matrix.outputs.outputs).items }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Ensure .docker exists
        run: |
          mkdir -p /github/home/.docker
          if ! [ -f /github/home/.docker/config.json ];then
            echo '{"auths":{}}' > /github/home/.docker/config.json
          fi

      - name: Login to ghcr
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - name: Get manifest cache
        uses: ./.github/actions/manifest-cache-restore
        with:
          key: manifest_${{ inputs.variant }}
          artifact: true

      - name: Get matrix
        id: matrix
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            args=""
            if [[ "${{ inputs.recreate }}" != "true" ]];then
              args="$args --missing"
            fi
            data="$(./make.py get-deltas --json $args ${{ inputs.variant }})"
            items="$(echo "$data" | jq -c 'length')"
            echo 'outputs<<EOF' >> $GITHUB_OUTPUT
            echo '{"matrix":' >> $GITHUB_OUTPUT
            if [[ $items -gt 0 ]];then
              echo "$data" | jq -c '{"include": .}' >> $GITHUB_OUTPUT
            else
              echo '{"include":[{"a":"","b":"","tag":""}]}' >> $GITHUB_OUTPUT
            fi
            echo ",\"items\":$items}" >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
            cat $GITHUB_OUTPUT
        env:
          TMPDIR: ${{ runner.temp }}
  run:
    name: ${{ matrix.a }} to ${{matrix.b}}
    if: ${{ needs.matrix.outputs.items > 0 }}
    runs-on: ubuntu-latest
    container: *container
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.variant-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup container
        uses: ./.github/actions/setup-container

      - name: Login to dockerhub
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - name: Mask registry passwords
        uses: ./.github/actions/mask-registry-passwords

      - name: Free up space
        uses: ./.github/actions/cleanup
        with:
          root: /run/host

      - name: Get manifest cache
        uses: ./.github/actions/manifest-cache-restore
        with:
          key: manifest_${{ inputs.variant }}
          path: ${{ github.workspace }}/.tmp/manifest_cache
          artifact: true

      - name: Build
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            args=""
            if [[ "${{ inputs.recreate }}" == "true" ]];then
              args="$args --force"
            fi
            if [[ "${{ inputs.push }}" == "true" ]];then
              args="$args --push"
            fi
            ./make.py delta $args --explicit ${{ matrix.a }} ${{ matrix.b }}
        env:
          TMPDIR: ${{ github.workspace }}/.tmp

      - name: Get image name
        id: image
        run: |
          python <<'EOF'
          import os, json, make
          from _os.podman import hex_to_base62, image_digest
          from _os import REPO
          a = hex_to_base62(image_digest(f"{REPO}:${{ matrix.a }}"))
          b = hex_to_base62(image_digest(f"{REPO}:${{ matrix.b }}"))
          with open(os.environ["GITHUB_OUTPUT"], 'a') as f:
            _ = f.write(f"tag={json.dumps(f"_diff-{a}-{b}")}\n")
            _ = f.write(f"image={json.dumps(REPO)}\n")
          EOF

      - name: Upload image artifact
        if: steps.build.outputs.updates == 'true'
        uses: ./.github/actions/upload-image
        with:
          image: ${{ steps.image.outputs.image }}
          name: ${{ steps.image.outputs.tag }}
          if-no-files-found: ignore
