name: Build an iso

on:
  workflow_call:
    inputs: &inputs
      variant:
        description: Which variant to generate an ISO for
        type: string
        required: true
      pull:
        description: Pull the latest image, or use the workflow artifact
        type: boolean
        default: false
        required: false
      offline:
        description: Offline installable?
        type: boolean
        default: true
        required: false
  workflow_dispatch:
    inputs: *inputs

permissions:
  contents: read
  packages: read

concurrency:
  group: iso-${{ inputs.variant }}
  cancel-in-progress: true

jobs:
  run:
    name: atomic-arch:${{ inputs.variant }} iso
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eeems/atomic-arch-builder:latest
      options: >-
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device /dev/fuse
        --tmpfs /tmp
        --tmpfs /run
        --userns=host
        -v /var/lib/containers:/var/lib/containers
        -v /:/run/host
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-container

      - name: Login to ghcr
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - uses: ./.github/actions/mask-registry-passwords

      - name: Free up space
        uses: ./.github/actions/cleanup
        with:
          root: /run/host

      - name: Download image artifact
        id: download
        if: ${{ !inputs.pull }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.variant }}

      - name: Load image artifact
        if: ${{ !inputs.pull }}
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            cd "${{ steps.download.outputs.download-path }}"
            zstdcat "${{ inputs.variant }}.tar.zstd" | podman load
            rm "${{ inputs.variant }}.tar.zstd"

      - name: Build
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            args=""
            if [[ "${{ inputs.offline }}" == "true" ]];then
              args="$args --no-local-image"
            fi
            ./make.py iso $args ${{ inputs.variant }}
        env:
          TMPDIR: ${{ runner.temp }}

      - name: Upload iso
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.offline && 'offline_' || 'online_' }}_atomic-arch-${{ inputs.variant }}.iso
          path: /var/lib/system/atomic-arch-${{ inputs.variant }}-*.iso
