name: Build manifest

on:
  workflow_dispatch:
    inputs: &inputs
      cache:
        description: Should the cache be used
        default: true
        required: false
        type: boolean
  workflow_call:
    inputs: *inputs

permissions:
  contents: read
  packages: write
  actions: write

concurrency:
  group: manifest-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  notifications:
    name: Clear notifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Clean cancellation notifications
        uses: ./.github/actions/clean-cancelled-notifications
        with:
          pat: ${{ secrets.NOTIFICATION_PAT }}

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Remove untagged containers older than 1 week
        run: |
          gh api \
            --paginate \
            "/users/Eeems/packages/container/arkes/versions" \
          | jq -r '
            .[]
            | select(.metadata.container.tags == [])
            | select( (.updated_at | fromdateiso8601) <= (now - 7*24*60*60))
            | .id
          ' \
          | xargs -I {} \
            gh api \
              --method DELETE \
              "/users/Eeems/packages/container/arkes/versions/{}"
        env:
          GH_TOKEN: ${{ github.token }}

  run:
    name: Build manifest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eeems/arkes-builder:${{ github.head_ref || github.ref_name }}
      options: >-
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device /dev/fuse
        --tmpfs /tmp
        --tmpfs /run
        --userns=host
        -v /:/run/host
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup container
        uses: ./.github/actions/setup-container

      - name: Login to ghcr
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - name: Mask registry passwords
        uses: ./.github/actions/mask-registry-passwords

      - name: Get manifest cache
        if: ${{ inputs.cache }}
        uses: ./.github/actions/manifest-cache-restore

      - name: Build
        uses: ./.github/actions/run-with-podman-service
        with:
          run: |
            args=""
            if [[ "$push" == "true" ]];then
              args="--push"
            fi
            ./make.py manifest $args
        env:
          TMPDIR: ${{ runner.temp }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Save manifest cache
        if: ${{ inputs.cache }}
        uses: ./.github/actions/manifest-cache-update
