name: Build manifest

on:
  pull_request: &on-filter
    branches:
      - master
    paths:
      - .github/workflows/manifest.yaml
      - make.py
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  actions: write

concurrency:
  group: manifest
  cancel-in-progress: true

jobs:
  run:
    name: Build manifest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eeems/atomic-arch-builder:latest
      options: >-
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --cap-add=SYS_ADMIN
        --cap-add=NET_ADMIN
        --device /dev/fuse
        --tmpfs /tmp
        --tmpfs /run
        --userns=host
        -v /var/lib/containers:/var/lib/containers
        -v /:/run/host
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Ensure .docker exists
        run: |
          mkdir -p /github/home/.docker
          if ! [ -f /github/home/.docker/config.json ];then
            echo '{"auths":{}}' > /github/home/.docker/config.json
          fi

      - name: Login to ghcr
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          auth_file_path: /run/containers/0/auth.json

      - name: Wait for all deltas to finish generating
        uses: NathanFirmo/wait-for-other-action@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "delta.yaml"

      - uses: actions/cache/restore@v4
        id: manifest-cache
        with:
          path: ${{ runner.temp }}/manifest_cache
          key: manifest-cache

      - name: Build
        shell: bash
        run: |
          mkdir -p /run/podman
          podman system service --time 0 unix:///run/podman/podman.sock &
          if [ ! -f /etc/containers/seccomp.json ];then
            cp seccomp.json /etc/containers/seccomp.json
          fi
          args=""
          if [[ "$push" == "true" ]];then
            args="--push"
          fi
          ./make.py manifest $args
          kill $(jobs -p) || true
        env:
          TMPDIR: ${{ runner.temp }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Remove old cache
        shell: bash
        run: |
          gh cache delete \
            -k "${{ steps.manifest-cache.outputs.cache-primary-key }}" \
            --repo "${{ github.repository }}"

      - uses: actions/cache/save@v4
        with:
          path: ${{ runner.temp }}/manifest_cache
          key: manifest-cache
