name: Sync images
on:
  workflow_dispatch:
    inputs: &inputs
      from:
        description: "Repository to sync from"
        default: ghcr.io
        type: string
        required: false
      to:
        description: "Repository to sync to"
        default: docker.io
        type: string
        required: false
  workflow_call:
    inputs: *inputs

permissions:
  contents: read
  packages: read

concurrency:
  group: sync-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  notifications:
    name: Clear notifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Clean cancellation notifications
        uses: ./.github/actions/clean-cancelled-notifications
        with:
          pat: ${{ secrets.NOTIFICATION_PAT }}

  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      variant-matrix: ${{ steps.matrix.outputs.variant-matrix }}
      variant-items: ${{ steps.matrix.outputs.variant-items }}
      diff-matrix: ${{ steps.matrix.outputs.diff-matrix }}
      diff-items: ${{ steps.matrix.outputs.diff-items }}
      explicit-matrix: ${{ steps.matrix.outputs.explicit-matrix }}
      explicit-items: ${{ steps.matrix.outputs.explicit-items }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: eeems
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Mask registry passwords
        uses: ./.github/actions/mask-registry-passwords

      - name: Generate matrix
        id: matrix
        shell: bash
        run: |
          set -e
          variants=$( \
            ./make.py config \
            | jq -r \
              '.variants | keys[] as $k | $k, ( [.[$k].templates[] | "\($k)-\(.)"] | join("\n") )' \
          )
          matrix=$(echo "_manifest $variants" | xargs -n1 echo)
          items=$(echo "$variants" | wc -l)
          echo 'explicit-matrix<<EOF' >> $GITHUB_OUTPUT
          if [[ $items -gt 0 ]];then
            echo "$matrix" \
            | jq -Rc '{"include":[{"tag":inputs | select(length > 0)}]}' \
            >> $GITHUB_OUTPUT
          else
            echo '{"include":[{"tag":""}]}' >> $GITHUB_OUTPUT
          fi
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "explicit-items=$items" >> $GITHUB_OUTPUT
          echo "Explicit Items: $items"

          # TODO use manifest instead of relying on tags, this allows
          #      prioritizing which diffs should be first
          data=$(cat <( \
            comm -23 \
              <(
                skopeo list-tags \
                  --retry-times 10 \
                  "docker://$from/$image" \
                | jq -r '.Tags.[]' \
                | sort \
              ) \
              <(
                skopeo list-tags \
                  --retry-times 10 \
                  "docker://$to/$image" \
                | jq -r '.Tags.[]' \
                | sort \
              ) \
          ))
          matrix=$( \
            printf '%s\n' "$data" \
            | grep -E \
              "^($(printf '%s\n' "$variants" | sed 's/[.^$*+?()|[\]{}]/\\&/g' | sed 's/$/_/' | paste -sd '|' -))" \
          )
          items=$(echo "$matrix" | wc -l)
          echo 'variant-matrix<<EOF' >> $GITHUB_OUTPUT
          if [[ $items -gt 0 ]];then
            echo "$matrix" \
            | jq -Rc '{"include":[{"tag":inputs | select(length > 0)}]}' \
            >> $GITHUB_OUTPUT
          else
            echo '{"include":[{"tag":""}]}' >> $GITHUB_OUTPUT
          fi
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "variant-items=$items" >> $GITHUB_OUTPUT
          echo "Variant Items: $items"

          matrix=$(echo "$data" | grep -E ^_diff-)
          items=$(echo "$matrix" | wc -l)
          if [[ $items -gt 256 ]];then
            matrix=$(echo "$matrix" | head -n256 || true)
            echo "::warning title=Diffs skipped::There are $items diffs, skipping some"
            items=256
          fi
          echo 'diff-matrix<<EOF' >> $GITHUB_OUTPUT
          if [[ $items -gt 0 ]];then
            echo "$matrix" \
            | jq -Rc '{"include":[{"tag":inputs | select(length > 0)}]}' \
            >> $GITHUB_OUTPUT
          else
            echo '{"include":[{"tag":""}]}' >> $GITHUB_OUTPUT
          fi
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "diff-items=$items" >> $GITHUB_OUTPUT
          echo "Diff Items: $items"

        env:
          from: ${{ inputs.from }}
          to: ${{ inputs.to }}
          image: eeems/atomic-arch

  sync-explicit:
    name: Sync eeems/atomic-arch:${{ matrix.tag }}
    runs-on: ubuntu-latest
    if: ${{ needs.matrix.outputs.explicit-items > 0 }}
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.explicit-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: eeems
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Mask registry passwords
        uses: ./.github/actions/mask-registry-passwords

      - name: Synchronize images
        shell: bash
        run: |
          skopeo copy \
            --multi-arch all \
            --retry-times 10 \
            "docker://$from/$image:$tag" \
            "docker://$to/$image:$tag"
        env:
          from: ${{ inputs.from }}
          to: ${{ inputs.to }}
          image: eeems/atomic-arch
          tag: ${{ matrix.tag }}

  sync-variants:
    name: Sync eeems/atomic-arch:${{ matrix.tag }}
    runs-on: ubuntu-latest
    if: ${{ needs.matrix.outputs.variant-items > 0 }}
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.variant-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: eeems
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Mask registry passwords
        uses: ./.github/actions/mask-registry-passwords

      - name: Synchronize images
        shell: bash
        run: |
          skopeo copy \
            --multi-arch all \
            --retry-times 10 \
            "docker://$from/$image:$tag" \
            "docker://$to/$image:$tag"
        env:
          from: ${{ inputs.from }}
          to: ${{ inputs.to }}
          image: eeems/atomic-arch
          tag: ${{ matrix.tag }}

  sync-diffs:
    name: Sync eeems/atomic-arch:${{ matrix.tag }}
    runs-on: ubuntu-latest
    if: ${{ needs.matrix.outputs.diff-items > 0 }}
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.diff-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: eeems
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Mask registry passwords
        uses: ./.github/actions/mask-registry-passwords

      - name: Synchronize images
        shell: bash
        run: |
          skopeo copy \
            --multi-arch all \
            --retry-times 10 \
            "docker://$from/$image:$tag" \
            "docker://$to/$image:$tag"
        env:
          from: ${{ inputs.from }}
          to: ${{ inputs.to }}
          image: eeems/atomic-arch
          tag: ${{ matrix.tag }}
