name: Sync images
on:
  pull_request: &on-filter
    branches:
      - master
    paths:
      - .github/workflows/sync.yaml
  push: *on-filter
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read
  packages: read

concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  notifications:
    name: Clear notifications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Clean cancellation notifications
        uses: ./.github/actions/clean-cancelled-notifications
        with:
          pat: ${{ secrets.NOTIFICATION_PAT }}

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - uses: ./.github/actions/mask-registry-passwords

      - name: Synchronize images
        shell: bash
        run: |
          set -e
          image=eeems/atomic-arch
          from=ghcr.io
          to=docker.io
          while read -r tag;do
            echo "::group::$tag"
            skopeo copy \
              --multi-arch all \
              --retry-times 10 \
              "docker://$from/$image:$tag" \
              "docker://$to/$image:$tag"
            echo "::endgroup::"
          done < <( \
            comm -23 \
              <(
                skopeo list-tags \
                  --retry-times 10 \
                  "docker://$from/$image" \
                | jq -r '.Tags.[]' \
                | sort \
              ) \
              <(
                skopeo list-tags \
                  --retry-times 10 \
                  "docker://$to/$image" \
                | jq -r '.Tags.[]' \
                | sort \
              ) \
          )
