name: Sync images
on:
  pull_request: &on-filter
    branches:
      - master
    paths:
      - .github/workflows/sync.yaml
  push: *on-filter
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read
  packages: read

concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Mask the Docker password (JWT)
        run: |
          CONFIG=""
          for path in \
            "${DOCKER_CONFIG:-}/config.json" \
            "${RUNNER_TEMP:-}/_temp/.docker/config.json" \
            "${HOME}/.docker/config.json"
          do
            if [[ ! -f "$path" ]]; then
              continue
            fi
            CONFIG="$path"
            echo "Masking auths in $CONFIG"
            jq -r '.auths | to_entries[] | .value.auth' "$CONFIG" \
            | while IFS= read -r auth; do
              [[ "$auth" == "null" ]] && continue
              token=$(echo "$auth" | base64 -d | cut -d: -f2)
              [[ -n "$token" ]] && echo "::add-mask::$token"
            done
          done
          if [[ -z "$CONFIG" ]]; then
            echo "No Docker config.json found â€“ nothing to mask"
          fi

      - name: Synchronize images
        shell: bash
        run: |
          set -e
          image=eeems/atomic-arch
          from=ghcr.io
          to=docker.io
          while read -r tag;do
            echo "::group::$tag"
            skopeo copy \
              --multi-arch all \
              --retry-times 10 \
              "docker://$from/$image:$tag" \
              "docker://$to/$image:$tag"
            echo "::endgroup::"
          done < <( \
            comm -23 \
              <(
                skopeo list-tags \
                  --retry-times 10 \
                  "docker://$from/$image" \
                | jq -r '.Tags.[]' \
                | sort \
              ) \
              <(
                skopeo list-tags \
                  --retry-times 10 \
                  "docker://$to/$image" \
                | jq -r '.Tags.[]' \
                | sort \
              ) \
          )
